CREATE INDEX idx_person_name ON person(UPPER(name));

SET ENABLE_SEQSCAN TO ON;
EXPLAIN ANALYSE
SELECT *
  FROM person AS p
  WHERE UPPER(p.name) = 'DMITRIY'

SET ENABLE_SEQSCAN TO OFF;
EXPLAIN ANALYSE
SELECT *
  FROM person AS p
 WHERE UPPER(p.name) = 'DMITRIY'